POST http://nihuleapi.herokuapp.com/register
Content-Type: application/json


{
    "email":"devnihule@gmail.com",
    "password":"1a1A1a1A"
}

###

GET http://nihuleapi.herokuapp.com/show

### 
post http://nihuleapi.herokuapp.com/addDailyReport
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldm5paHVsZUBnbWFpbC5jb20iLCJpYXQiOjE2MDM0NTUyODYsImV4cCI6MTYwMzQ1ODg4Nn0.hMRKDdMrsb9nqdM6c3bvNrFXRGcjh-2ghlbV0eyXszs